stages:
  - release-images
  - triggers

variables:
  IMAGE_REF: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

release-images:
  stage: release-images
  script:
    - docker build -t smart_transport -f Dockerfile .
    - docker tag smart_transport $IMAGE_REF
    - docker push $IMAGE_REF
  only:
    - main

ci_cd_demo:
  variables:
    UPSTREAM_REGISTRY_IMAGE: $CI_REGISTRY_IMAGE
  stage: triggers
  trigger: ritm/ci-cd-demo
  only:
    - main
